### PR TITLE
Fetch boardgame stats

### PR DESCRIPTION
**Pull request by anithri**
I added the ability to optionally fetch the statistics addition and parse it into a member object of the game itself.

the geek allows adding `stats=`` to get the statistics package that includes the games rating, game rank in 1 or more categories, number owened, etc.  

I created the BggStats object as a simple data object, and the smaller GameRanks object to encapsulate the 0 or more game ranks it might have.

I updated the xml file with the latest data and statistics, altered the specs a bit to update game data that has changed.

### CODE REVIEW

**Comment by anithri** [comment]
I'm not sure what else my personal project will need of this, but the gem really needs a new strategy moving forward I think.

The greatest weakness of the Game, Link, Stats, and GameRanks gem is that they are parsing themselves for the most part.  And the more elements that are incorporated the more bloated those classes will get.

What I'm thinking instead is the separate the parsing from the internal storage of  the data.
 Have the parser concentrate on reducing it to a well understood data structure, and then using that structure to output as objects, json, yaml...

I like the https://github.com/solnic/virtus project a lot.  
``` my game = Bgg::Game.by_id(84876, :expansions,:simple_links, :comments, :statistics) ```
where you can customize how much you need or want from the api.

The parser to me is just to find some way to shove the xml data into a fair json version of it.  Ideally we construct a nested hash construction using arrays, strings, and hashes.  so with one data structure you can populate a whole tree easily.

I also think virtus is a good platform to build in a lazy load system for expansions

**Comment by anithri** [comment]
Ugh, might need some commit love before accepting.

**Comment by anithri** [comment]
I'd like to add in a caching system that we could inject to allow easy use of memcached or Rails.cache.  I want to be kind to the site, and the cache duration could easily be as long as you want, it's not exactly stock market data.

**Comment by anithri** [comment]
the last project i kind of have in mind is to see if I can dial in some scraping action on pages in the site that offer things not available from the API.  things like the Top 100 games and the description of 'Set Collection' games.  I'd like to have an understanding of any changes that might be made to the system before I start to implement though

I also need to check the terms and services to make sure that will be ok,

**Comment by jemiahlee** [comment]
ok. sorry I've been pretty busy, I'll try to take a look tonight.

**Pull request closed without merging**
