### PR TITLE
User refactor

### PR DESCRIPTION
**Pull request by craineum**
Long time... but I am determined to finish this!

I found a couple of bugs in the guild result object, which I fixed then back filled some tests to cover the other result objects so that doesn't happen again.

### CODE REVIEW

**Comment by jemiahlee** [comment]
I'm gonna come back to a comment I made (obviously a while ago :smiley:) that I think some of the rearrangement is making the API more difficult to use. I don't think a user of the API should need to know all of the internal structure to be able to make requests.

So for example, moving BGG::User to BGG::Request::User isn't a change that makes the API easier to use and forces the API user to know more about the layout of the package than about the conceptual idea of a BGG User.

I would also say that it's ok to have a front-end API that utilizes the backend objects, giving callers an API to use which reflects the conceptual way that the objects are in the BGG system.

**Comment by craineum** [comment]
Agree with what you are saying.  No one needs to use BGG::Request::User, but it is available to them.  Still using the root BGG to access all the request objects.  So a simple call to BggApi.user works just as well.

Sorry, I know there was something I was going to go back and refactor after I got thru all the functionality based on a previous comment.  Just have the 'thing' object left.

If you don't like the direction, no biggy can back stuff out, and we can start over :)  I am easy.

**Comment by jemiahlee** [comment]
Well, I'm not suggesting starting over. Just that I think we'll need to re-assess the client-facing API at some point.

**Comment by craineum** [comment]
Agreed, just want to finish something :)

**Comment by jemiahlee** [comment]
Ok, I've had a hellish couple of weeks at work but will do my best to get to this over the weekend. Sorry for the delay.

**Comment by jemiahlee** [comment]
lgtm

One other thing that we'll need to do sooner rather than later is switch everything to use the HTTPS URLs. The HTTP one has/is going away.

**Pull request merged**
